ktor:
  application:
    modules:
      - io.github.gunkim.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor realworld"
database:
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
  driver: "org.h2.Driver"
  user: "root"
  password: ""